# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160216_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images/%Y/%m/%d'),
        ),
    ]
