# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='static/images/avatar.jpg', upload_to='profile_images/%Y/%m/%d'),
        ),
    ]
