# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=170)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
    ]
