# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 03:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160216_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='staffs', to=settings.AUTH_USER_MODEL),
        ),
    ]
