# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 21:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160216_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 16, 21, 37, 50, 366002, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=datetime.datetime(2016, 2, 16, 21, 38, 3, 263195, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 16, 21, 38, 16, 67292, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 16, 21, 38, 26, 559658, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
