# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20160219_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 19, 11, 43, 1, 210442, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
