# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20160414_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='comments',
            field=models.ManyToManyField(blank=True, to='events.Comment'),
        ),
    ]
